name: Build e Deploy com ArgoCD

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Definir TAG de imagem com hash do commit
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        # Ou para timestamp:
        # run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/loteria:${{ env.IMAGE_TAG }} .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/loteria:${{ env.IMAGE_TAG }}

      - name: Clonar repositório de infraestrutura
        uses: actions/checkout@v3
        with:
          repository: sueliopontes/loteria-infra-deploy
          token: ${{ secrets.LOTERIA_TOKEN }}
          path: infra
          persist-credentials: false

      - name: Atualizar tag da imagem no deployment.yaml
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/loteria:${{ env.IMAGE_TAG }}|' infra/k8s/dev/deployment.yaml

      - name: Commit e push
        run: |
          cd infra
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Atualiza imagem para ${{ env.IMAGE_TAG }}" || echo "Nada para commitar"
          git push https://x-access-token:${{ secrets.LOTERIA_TOKEN }}@github.com/sueliopontes/loteria-infra-deploy.git HEAD:main
